### PR TITLE
Added: support for custom nonlinear constraints `gc` in `NonLinMPC`

### PR DESCRIPTION
**Pull request by franckgaga**

### CODE REVIEW

**Comment by baggepinnen** [comment]
just a little note, I've never really come across the term "economic constraints" before, is this from some particular book on nonlinear MPC? I use nonlinear MPC with nonlinear constraints very often, but it almost never have an economic interpretation. Would it perhaps be more generic to call them "nonlinear constraints"? I'm thinking that someone who want's to add safety constraints such as collision avoidance will not find what they are looking for, not knowing to look for "economic constraints".

**Comment by franckgaga** [comment]
That's a good point. I named them economic constraints merely for consistency with my current notation. The nonlinear constraint function will not receive $\mathbf{U}$, $\mathbf{\hat{Y}}$ and $\mathbf{\hat{D}}$ but the slightly longer version appended with the $E$ subscript:

image

It is also consistent with the custom objective term $J_E$

> Would it perhaps be more generic to call them "nonlinear constraints"?

It would not be precise enough since there is also the plant output and the terminal bounds that are also nonlinear (if the plant model is nonlinear). It's not a replacement of the nonlinear constraints but an addition to the current nonlinear constraints. Maybe just naming them "custom nonlinear constraints" would be sufficient. I would also change my notation to:

```math
J_E(\mathbf{\bar{U}, \bar{Y}, \bar{D}, p}) \quad \text{and} \quad \mathbf{g_C}(\mathbf{\bar{U}, \bar{Y}, \bar{D}, \epsilon, p})
```
with the new notation $\mathbf{\bar{U}} = \mathbf{U}_E$, $\mathbf{\bar{Y}} = \mathbf{\hat{Y}}_E$ and $\mathbf{\bar{D}} = \mathbf{\hat{D}}_E$.

While we are at it, do you think that it's a bad idea to name the custom objective term the economic term? (but renaming it and changing the notation would be a breaking change since they are keyword arguments.)

**Comment by baggepinnen** [comment]
> While we are at it, do you think that it's a bad idea to name the custom objective term the economic term? 

Not necessarily bad, but I'd imagine that many aren't familiar with the term. 

> but renaming it and changing the notation would be a breaking change since they are keyword arguments.

One way of changing stuff like this in a non-breaking way is to introduce the new keyword, keep the old, and then do something like
```julia
function fun(; new = default, old = nothing)
    new = something(old, new)
end
```

the function `something` returns the first argument that is not `nothing`. If the old keyword is removed from the docs, no one will use it in the future, but existing usage will continue to work.

**Comment by franckgaga** [comment]
@baggepinnen there is no test at all for now so it's very experimental. I'll implement this soon. 🙂

But for now, do you have any comments about the documentation ? (see `NonLinMPC` in the dev doc)

**Comment by franckgaga** [comment]
One problem I see right now is how it's easy to forget to assign the `nc` keyword argument in combination with the custom nonlinear constraint function. I'm thinking of calling the `JE` and the `gc` function at least once in the `NonLinMPC` constructor and emit some warnings to guide the user a little bit. 

Just calling `sim!` on `NonLinModel` is a quick way to troubleshoot bugs in the `f` and `h` functions. There is now equivalent functionalities for the `JE` and `gc` args right now...

**Pull request merged**
